/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as NyheterRouteImport } from './routes/nyheter'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NyheterIndexRouteImport } from './routes/nyheter/index'
import { Route as NyheterSlugRouteImport } from './routes/nyheter/$slug'

const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const NyheterRoute = NyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NyheterIndexRoute = NyheterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NyheterRoute,
} as any)
const NyheterSlugRoute = NyheterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NyheterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/nyheter': typeof NyheterRouteWithChildren
  '/tjanster': typeof TjansterRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/nyheter/': typeof NyheterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/tjanster': typeof TjansterRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/nyheter': typeof NyheterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/nyheter': typeof NyheterRouteWithChildren
  '/tjanster': typeof TjansterRoute
  '/nyheter/$slug': typeof NyheterSlugRoute
  '/nyheter/': typeof NyheterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/nyheter'
    | '/tjanster'
    | '/nyheter/$slug'
    | '/nyheter/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/tjanster' | '/nyheter/$slug' | '/nyheter'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/nyheter'
    | '/tjanster'
    | '/nyheter/$slug'
    | '/nyheter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  NyheterRoute: typeof NyheterRouteWithChildren
  TjansterRoute: typeof TjansterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyheter': {
      id: '/nyheter'
      path: '/nyheter'
      fullPath: '/nyheter'
      preLoaderRoute: typeof NyheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyheter/': {
      id: '/nyheter/'
      path: '/'
      fullPath: '/nyheter/'
      preLoaderRoute: typeof NyheterIndexRouteImport
      parentRoute: typeof NyheterRoute
    }
    '/nyheter/$slug': {
      id: '/nyheter/$slug'
      path: '/$slug'
      fullPath: '/nyheter/$slug'
      preLoaderRoute: typeof NyheterSlugRouteImport
      parentRoute: typeof NyheterRoute
    }
  }
}

interface NyheterRouteChildren {
  NyheterSlugRoute: typeof NyheterSlugRoute
  NyheterIndexRoute: typeof NyheterIndexRoute
}

const NyheterRouteChildren: NyheterRouteChildren = {
  NyheterSlugRoute: NyheterSlugRoute,
  NyheterIndexRoute: NyheterIndexRoute,
}

const NyheterRouteWithChildren =
  NyheterRoute._addFileChildren(NyheterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  NyheterRoute: NyheterRouteWithChildren,
  TjansterRoute: TjansterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
